export enum Errors {
    ERROR_CODE_UNDEFINED = 0,

    INVALID_ARGUMENT = 3,

    NOT_FOUND = 5,
    ACCOUNT_NOT_FOUND = 501,
    POOL_NOT_FOUND = 502,
    NETWORK_NOT_FOUND = 503,

    ALREADY_EXIST = 6,

    PERMISSION_DENIED = 7,

    INTERNAL_ERROR = 13,

    UNAVAILABLE = 14,

    UNAUTHENTICATED = 16,
}
